// book package
export const CREATE_BOOK_PACKAGE_SUCCESS = 'CREATE_BOOK_PACKAGE_SUCCESS';
export const CREATE_BOOK_PACKAGE_FAILURE = 'CREATE_BOOK_PACKAGE_FAILURE';
export const GET_BOOK_PACKAGES_SUCCESS = 'GET_BOOK_PACKAGES_SUCCESS';
export const GET_BOOK_PACKAGES_FAILURE = 'GET_BOOK_PACKAGES_FAILURE';
export const GET_BOOK_PACKAGE_SUCCESS = 'GET_BOOK_PACKAGE_SUCCESS';
export const GET_BOOK_PACKAGE_FAILURE = 'GET_BOOK_PACKAGE_FAILURE';
export const UPDATE_BOOK_PACKAGE_SUCCESS = 'UPDATE_BOOK_PACKAGE_SUCCESS';
export const UPDATE_BOOK_PACKAGE_FAILURE = 'UPDATE_BOOK_PACKAGE_FAILURE';
export const DELETE_BOOK_PACKAGE_SUCCESS = 'DELETE_BOOK_PACKAGE_SUCCESS';
export const DELETE_BOOK_PACKAGE_FAILURE = 'DELETE_BOOK_PACKAGE_FAILURE';
