export const CONTACT_EXPEDITION_SUCCESS = 'CONTACT_EXPEDITION_SUCCESS';
export const CONTACT_EXPEDITION_FAILURE = 'CONTACT_EXPEDITION_FAILURE';
export const CONTACT_SUCCESS_PACKAGE = 'CONTACT_SUCCESS_PACKAGE';
export const CONTACT_FAILURE_PACKAGE = 'CONTACT_FAILURE_PACKAGE';
