export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCES = 'LOGOUT_SUCCES';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GET_USERS = 'GET_USERS';

export const GET_PACKAGES = 'GET_PAKAGES';
